# Generated by Django 4.1.4 on 2022-12-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('admission_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('student_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('parents_name', models.CharField(max_length=100)),
                ('parent_number', models.IntegerField(unique=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass')),
            ],
        ),
    ]
