# Generated by Django 4.1.4 on 2022-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teachersubjectinfo_student'),
        ('student', '0008_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='subject',
            field=models.ManyToManyField(to='teacher.teachersubjectinfo'),
        ),
    ]
