# Generated by Django 4.1.4 on 2022-12-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teachersubjectinfo_student'),
        ('student', '0009_studentclass_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentSubject',
        ),
        migrations.CreateModel(
            name='StudentClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
        ),
    ]
