# Generated by Django 4.1.4 on 2022-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_studentclass_studentsubject_studentclassname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassname',
            name='student',
        ),
        migrations.AddField(
            model_name='studentclassname',
            name='student',
            field=models.ManyToManyField(to='student.studentinfo'),
        ),
    ]
