# Generated by Django 4.1.4 on 2022-12-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_group_student_delete_studentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='student.studentclass'),
        ),
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(null=True, related_name='student_name', to='student.studentinfo'),
        ),
    ]
