# Generated by Django 4.1.4 on 2022-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_group_group_alter_group_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(related_name='student_name', to='student.studentinfo'),
        ),
    ]
