# Generated by Django 4.1.4 on 2022-12-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teachersubjectinfo_student'),
        ('student', '0020_groupdetail_remove_group_student_group_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('subject', models.ManyToManyField(to='teacher.teachersubjectinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.DeleteModel(
            name='GroupDetail',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentclass'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
