# Generated by Django 4.1.4 on 2022-12-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_teacherinfo_subject_teacherinfo_subject'),
        ('student', '0021_studentclass_remove_group_subject_delete_groupdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo'),
        ),
    ]
