# Generated by Django 4.1.4 on 2022-12-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_sub_name_teachersubjectinfo_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubjectinfo',
            name='student',
        ),
    ]
