# Generated by Django 4.1.4 on 2022-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teachersubjectinfo_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='subject',
            field=models.ManyToManyField(to='teacher.teachersubjectinfo'),
        ),
    ]
