# Generated by Django 4.1.4 on 2022-12-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teacherinfo_subject_teacherinfo_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teachersubjectinfo'),
        ),
    ]
